/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author PC
 */
public class ViewUserUI extends javax.swing.JFrame {

    /**
     * Creates new form NewUserr
     */
    public ViewUserUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1NEWUSERACCOUNT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonFilter = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1NEWUSERACCOUNT.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1NEWUSERACCOUNT.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1NEWUSERACCOUNT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1NEWUSERACCOUNT.setText("MANAGE USERS");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Apple Store\\icon\\team.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1NEWUSERACCOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1NEWUSERACCOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Full Name", "Age", "Address", "Email", "User Type"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jButtonFilter.setBackground(new java.awt.Color(0, 102, 153));
        jButtonFilter.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jButtonFilter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFilter.setText("Filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jComboBox.setBackground(new java.awt.Color(0, 102, 153));
        jComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Manager", "Cashier" }));

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(0, 102, 153));
        jButtonUpdate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("View");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(0, 102, 153));
        jButtonDelete.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 102, 153));
        update.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonUpdate)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFilter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFilter)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(update)
                    .addComponent(jButtonDelete)
                    .addComponent(jButton2)
                    .addComponent(jButtonBack))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
         this.hide();
        ManagerUI frm = new ManagerUI();
        frm.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        String filepath = "C:\\Apple Store\\User.txt";
        File file = new File(filepath);

        try {
            BufferedReader br = new  BufferedReader (new FileReader (file));

            String firstLine = br.readLine().trim();
            String[] coloumnName = firstLine.split(",");
            DefaultTableModel model = ( DefaultTableModel)jTable2.getModel();
            model.setColumnIdentifiers(coloumnName);

            Object[] tableLines = br.lines().toArray();

            for(int i =0; i<tableLines.length;i++)
            {
                String line  = tableLines[i].toString().trim();
                String[]dataRow = line.split(",");
                model.addRow(dataRow);
            }

        }
        catch (IOException ex) {
            Logger.getLogger(ViewUserUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        DefaultTableModel tb1 = (DefaultTableModel) jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow != -1) {
            tb1.removeRow(selectedRow);
            updateFileFromTableModel(tb1); // Call the method to update the text file
            JOptionPane.showMessageDialog(this, "User Deleted successfully");
        } else {
            if (tb1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty, no user to delete.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            }
        }
        }

        private void updateFileFromTableModel(DefaultTableModel model) {
            String filepath = "C:\\Apple Store\\User.txt";
            File file = new File(filepath);

            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
                int rowCount = model.getRowCount();
                int colCount = model.getColumnCount();

                // Write column names to the file
                StringBuilder colHeader = new StringBuilder();
                for (int col = 0; col < colCount; col++) {
                    colHeader.append(model.getColumnName(col));
                    if (col < colCount - 1) {
                        colHeader.append(",");
                    }
                }
                bw.write(colHeader.toString());
                bw.newLine();

                // Write data rows to the file
                for (int row = 0; row < rowCount; row++) {
                    StringBuilder dataRow = new StringBuilder();
                    for (int col = 0; col < colCount; col++) {
                        dataRow.append(model.getValueAt(row, col));
                        if (col < colCount - 1) {
                            dataRow.append(",");
                        }
                    }
                    bw.write(dataRow.toString());
                    bw.newLine();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow != -1) {
            // Get the data from the selected row and columns
            String[] columnData = new String[tableModel.getColumnCount()];
            for (int i = 0; i < columnData.length; i++) {
                columnData[i] = tableModel.getValueAt(selectedRow, i).toString();
            }

            // Show input fields to update the data
            String[] updatedColumnData = new String[columnData.length];
            String[] columnNames = { "User ID:", "Full Name:", "Age:", "Address:", "Email:","User Type:" }; // Replace with actual column names
            JComboBox<String> itemTypeComboBox = new JComboBox<>(new String[] { "Manager", "Cashier" });

            for (int i = 0; i < columnData.length; i++) {
                if (i == 3) { // "Item Type" column
                    itemTypeComboBox.setSelectedItem(columnData[i]);
                    int option = JOptionPane.showOptionDialog(
                        this,
                        itemTypeComboBox,
                        "Select updated User Type",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        null,
                        itemTypeComboBox.getSelectedItem()
                    );
                    if (option == JOptionPane.OK_OPTION) {
                        updatedColumnData[i] = itemTypeComboBox.getSelectedItem().toString();
                    } else {
                        // If the user canceled the update, stop and show a message
                        JOptionPane.showMessageDialog(this, "Update canceled");
                        return;
                    }
                } else {
                    String input = JOptionPane.showInputDialog(this, "Enter updated data for " + columnNames[i], columnData[i]);
                    if (input == null) {
                        // If the user canceled the update, stop and show a message
                        JOptionPane.showMessageDialog(this, "Update canceled");
                        return;
                    }
                    updatedColumnData[i] = input;
                }
            }

            // Update the table if the user provided updated data
            for (int i = 0; i < updatedColumnData.length; i++) {
                tableModel.setValueAt(updatedColumnData[i], selectedRow, i);
            }
            //Update the data in the text file
            updateFileFromTableModel(tableModel);

            // Show a success message
            JOptionPane.showMessageDialog(this, "Update successful");
        } else {
            // Show a message if no row is selected
            JOptionPane.showMessageDialog(this, "Please select a row to update");
        }

        
    }//GEN-LAST:event_updateActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed

        // Get the selected item type from the combo box
        String selectedItemType = jComboBox.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable2.setRowSorter(sorter);

        // Set the RowFilter for the TableRowSorter to filter data based on selected item type
        if (!selectedItemType.equals("All")) {
            RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter(selectedItemType, 5); // 5 is the column index for "Item Type"
            sorter.setRowFilter(rf);
        } else {
            sorter.setRowFilter(null); // Remove the filter if "All" is selected
        }

    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);

        // Remove any existing filters
        TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) jTable2.getRowSorter();
        if (sorter != null) {
            sorter.setRowFilter(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1NEWUSERACCOUNT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
